language: python
dist: trusty
sudo: required

services:
  - docker

before_install:
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
  - sudo apt-get update -qq
  - sudo apt-get install -y shellcheck
  - sudo apt-get install -y -o Dpkg::Options::="--force-confold" --force-yes docker-engine

install:
  - pip install git+https://github.com/ansible/ansible-container.git 

script:
  - docker version
  - docker-compose version
  - docker info
  - mkdir -p tests
  - cd tests
  - ansible-container init
  - echo "Installing and testing git+https://github.com/${TRAVIS_REPO_SLUG},${TRAVIS_COMMIT}"
  - ansible-container install git+https://github.com/${TRAVIS_REPO_SLUG},${TRAVIS_COMMIT}
  # Travis complains about a port conflict
  - sed 's/5432:5432/6000:5432/' ansible/container.yml >ansible/tmp.yml
  - mv ansible/tmp.yml ansible/container.yml
  - cat ansible/container.yml
  - ansible-container build
  - ansible-container run -d
  # Our default database should exist, and we should be able to log into it.
  - ansible-container exec -i -t ansible_postgres_1 psql -U admin -d mydb <<-EOSQL
         SELECT CURRENT_TIME;
        EOSQL

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
