- name: Remove comments
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - name: Remove comments
    lineinfile:
      dest: ../ansible/container.yml
      regexp: '^  #'
      state: absent

