- name: Update container.yml
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - name: Change expose
    lineinfile:
      dest: ../ansible/container.yml
      regexp: 'expose:'
      line: '    ports:'

  - name: Change 5432
    lineinfile:
      dest: ../ansible/container.yml
      regexp: '- 5432'
      line: '    - 6000:5432'
