- name: Initialize the database
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    postgres_initdb_args: "{{ lookup('env', 'POSTGRES_INITDB_ARGS') }}"
    pgdata: /var/lib/pgsql/data
    postgres_db: "{{ lookup('env', 'POSTGRES_DB') }}"
    postgres_user: "{{ lookup('env', 'POSTGRES_USER') }}"
    postgres_pass: "{{ lookup('env', 'POSTGRES_PASS') }}"

  tasks:
    - name: Init the database
      command: "initdb -D {{ pgdata }} {{ postgres_initdb_args }}"
    
    - name: Update pg_hba.conf 
      lineinfile:
        dest: "{{ pgdata }}/pg_hba.conf"
        line: "host         all         all         0.0.0.0/0         md5"
   
    - name: Update postgresql.conf
      lineinfile:
        dest: "{{ pgdata }}/postgresql.conf"
        line: "{{ item.line }}"
        regexp: "{{ item.regexp }}" 
      with_items:
        - line: "listen_addresses = '*'"
          regexp: "^#listen_address"
        - line: "port = 5432"
          regexp: "^#port" 

    - name: Tempalte sql 
      template:
        src: ./createdb.j2.sql
        dest: ./createdb.sql 
    
    - name: Start pg_ctl in the background  
      command: "pg_ctl -D {{ pgdata }} -o \"-c listen_addresses=\'localhost\'\" -w start"
    
    - name: Create the database 
      command: psql -v ON_ERROR_STOP=1 --username postgres -a -f ./createdb.sql

    - name: Remove sql
      file:
        path: ./createdb.sql
        state: absent

    - name: Stop pg_ctl
      command: "pg_ctl -D {{ pgdata }} -m fast -w stop"

